name: Build WinUI 3 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: msbuild TranslateUI.sln /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build solution
      run: msbuild TranslateUI.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PublishTrimmed=false /p:PublishSingleFile=false

    - name: Create MSIX package
      run: msbuild TranslateUI.sln /t:Publish /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:GenerateAppInstallerFile=false /p:PublishTrimmed=false /p:PublishSingleFile=false

    - name: Find MSIX package
      id: find_msix
      run: |
        echo "msix_path=$(find . -name '*.msix')" >> $GITHUB_ENV
        echo "appinstaller_path=$(find . -name '*.appinstaller')" >> $GITHUB_ENV

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX-Package
        path: ${{ env.msix_path }}
