name: Build WinUI 3 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60  # 设置超时时间为60分钟

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: "P:\actions\setup-dotnet"

    - name: Setup MSBuild
      uses: "P:\actions\setup-msbuild"

    - name: Restore NuGet packages
      run: msbuild D:\source\TranslateUI\TranslateUI.sln /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build solution
      run: msbuild D:\source\TranslateUI\TranslateUI.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PublishTrimmed=false /p:PublishSingleFile=false

    - name: Create MSIX package
      run: msbuild D:\source\TranslateUI\TranslateUI.sln /t:Publish /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:GenerateAppInstallerFile=false /p:PublishTrimmed=false /p:PublishSingleFile=false

    - name: Find MSIX package
      id: find_msix
      run: |
        echo "Finding MSIX package..."
        echo "msix_path=$(find D:\source\TranslateUI -name '*.msix')" >> $GITHUB_ENV
        echo "appinstaller_path=$(find D:\source\TranslateUI -name '*.appinstaller')" >> $GITHUB_ENV
        echo "MSIX package found."

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX-Package
        path: ${{ env.msix_path }}
